language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
# command to install dependencies
install:
  - "pip install . --use-mirrors"
  - "pip install nose coverage"
# command to run tests
script: nosetests
